program: run_sweep.py
command:
  - python3
  - ${program}
method: grid
metric:
  name: charts/episodic_return
  goal: maximize
parameters:
  lr:
    values: [1e-5, 5e-5, 1e-4, 2e-4, 5e-4, 1e-3]
  # Fixed parameters
  env_name:
    value: "Craftax-Classic-Symbolic-v1"
  num_envs:
    value: 1024
  total_timesteps:
    value: 100000000  # 100M timesteps
  num_steps:
    value: 64
  update_epochs:
    value: 4
  num_minibatches:
    value: 8
  gamma:
    value: 0.99
  gae_lambda:
    value: 0.8
  clip_eps:
    value: 0.2
  ent_coef:
    value: 0.01
  vf_coef:
    value: 0.5
  max_grad_norm:
    value: 1.0
  activation:
    value: "tanh"
  anneal_lr:
    value: true
  debug:
    value: true
  jit:
    value: true
  use_wandb:
    value: true
  save_policy:
    value: false
  num_repeats:
    value: 1
  layer_size:
    value: 512
  use_optimistic_resets:
    value: true
  optimistic_reset_ratio:
    value: 16
  max_num_skills:
    value: 3
  diayn_reward_coef:
    value: 0.1